version: "3.9"

services:

  fraud-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: fraud_detection_api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - mlflow_data:/mlflow

volumes:
  mlflow_data: